#!/bin/sh -e
# Prints the full path to a file in the alternatives system.

case "$1" in ''|--help|-h)
    printf '\033[1;33m-> \033[m%s\n' "usage: ${0##*/} [pkg] [command]"
    exit 0; esac

cpt-list "$1" >/dev/null

[ "$2" ]
file="/var/db/cpt/choices/$1$(printf '%s' "$2" | sed 's#/#>#g')"
[ -f "$file" ] || {
    printf '\033[1;33m!> \033[1;36m%s \033[m%s\n' "$1" "choice '$2' not found" >&2
    exit 1
}
printf '%s\n' "$file"
